//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WitsClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockedPlayers
    {
        public int blockId { get; set; }
        public string player { get; set; }
        public string blockedPlayer { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Players Players1 { get; set; }
    }
}
