//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WitsClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friends
    {
        public int friendshipId { get; set; }
        public string principalPlayer { get; set; }
        public string friend { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Players Players1 { get; set; }
    }
}
