//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WitsClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int questionId { get; set; }
        public string questionES { get; set; }
        public string questionEN { get; set; }
        public string answerES { get; set; }
        public string answerEN { get; set; }
        public Nullable<int> trueAnswer { get; set; }
    }
}
