//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WitsClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int questionId { get; set; }
        public string questionES { get; set; }
        public string questionEN { get; set; }
        public string answerES { get; set; }
        public string answerEN { get; set; }
        public Nullable<int> trueAnswer { get; set; }
    }
}
