//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WitsClasses
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WitsAndWagersEntities : DbContext
    {
        public WitsAndWagersEntities()
            : base("name=WitsAndWagersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlockedPlayers> BlockedPlayers { get; set; }
        public virtual DbSet<Celebrations> Celebrations { get; set; }
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<ProfilePictures> ProfilePictures { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
    }
}
