//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WitsClasses
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WitsAndWagersEntities : DbContext
    {
        public WitsAndWagersEntities()
            : base("name=WitsAndWagersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlockedPlayers> BlockedPlayers { get; set; }
        public virtual DbSet<Celebrations> Celebrations { get; set; }
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<ProfilePictures> ProfilePictures { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
    }
}
